//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManageDBEntities : DbContext
    {
        public HotelManageDBEntities()
            : base("name=HotelManageDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckOut> CheckOut { get; set; }
        public virtual DbSet<Commodity> Commodity { get; set; }
        public virtual DbSet<Commodity_Consume> Commodity_Consume { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Regulations> Regulations { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Room_Commodity> Room_Commodity { get; set; }
        public virtual DbSet<Room_Discount> Room_Discount { get; set; }
        public virtual DbSet<Room_State> Room_State { get; set; }
        public virtual DbSet<Room_Type> Room_Type { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Staff_Ddentity> Staff_Ddentity { get; set; }
        public virtual DbSet<Staff_Dept> Staff_Dept { get; set; }
        public virtual DbSet<Staff_State> Staff_State { get; set; }
        public virtual DbSet<Room_Amount> Room_Amount { get; set; }
        public virtual DbSet<Commodity_Purchase> Commodity_Purchase { get; set; }
    }
}
