//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime EstablishDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.DateTime DeleteDate { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> ConsumeId { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Name { get; set; }
        public string IDCard { get; set; }
        public string Phone { get; set; }
        public bool Sex { get; set; }
        public Nullable<decimal> ActualMoney { get; set; }
        public System.DateTime EstimatedTime { get; set; }
        public Nullable<int> LiveDays { get; set; }
    }
}
