//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> Room_TypeId { get; set; }
        public Nullable<int> Room_DiscountId { get; set; }
        public Nullable<int> Room_AmountId { get; set; }
        public string GoodLuckNum { get; set; }
        public string FloorNum { get; set; }
        public string Number { get; set; }
        public string CompleteNum { get; set; }
        public Nullable<int> Room_CommodityId { get; set; }
        public Nullable<int> Room_StateId { get; set; }
    }
}
