//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public System.DateTime EstablishDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public bool Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Nation { get; set; }
        public int DeptId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Staff_StateId { get; set; }
        public Nullable<int> Staff_DdentityId { get; set; }
    }
}
